### ISSUE TITLE
Use

### ISSUE THREAD

**Issue by yd-915** [PabloFLPs/Send-Email-API#1]
Hi, 

I like your project. I was wondering if I could use your project for commercial purposes.
Thanks.

**Comment by PabloFLPs** [comment]
Sure! No problem, you can use it freely. Just clone my repository and create your own deployed application, because my app uses a free license, so it cannot be used with a large amount of requests. I am happy to know that you liked this project! 😄

**Comment by yd-915** [comment]
Thanks man. Respect!
